---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask-for-a-date-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ask-for-a-date-app
  template:
    metadata:
      labels:
        app: ask-for-a-date-app
    spec:
      containers:
      - name: ask-for-a-date-app
        image: rameshkumarverma/ask-for-a-date-app:latest
        ports:
        - containerPort: 80   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ask-for-a-date-app-service
spec:
  selector:
    app: ask-for-a-date-app
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 80
  type: LoadBalancer
